=== tyorka-shop/admin.tyorka.com/packages/server/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "InstaConfig": {
      "properties": {
        "access_token": {
          "type": "string"
        },
        "instagram_id": {
          "type": "string"
        }
      },
      "required": [
        "access_token",
        "instagram_id"
      ],
      "type": "object"
    },
    "PublicSiteConfig": {
      "properties": {
        "folder": {
          "type": "string"
        }
      },
      "required": [
        "folder"
      ],
      "type": "object"
    },
    "SessionServiceConfig": {
      "properties": {
        "url": {
          "type": "string"
        }
      },
      "required": [
        "url"
      ],
      "type": "object"
    }
  },
  "description": "This file was automatically generated by joi-to-typescript Do not modify this file manually",
  "properties": {
    "imagesFolder": {
      "type": "string"
    },
    "insta": {
      "$ref": "#/definitions/InstaConfig"
    },
    "port": {
      "type": "string"
    },
    "publicSite": {
      "$ref": "#/definitions/PublicSiteConfig"
    },
    "secret": {
      "type": "string"
    },
    "sessionService": {
      "$ref": "#/definitions/SessionServiceConfig"
    },
    "storeFolder": {
      "type": "string"
    }
  },
  "required": [
    "imagesFolder",
    "insta",
    "port",
    "publicSite",
    "secret",
    "sessionService",
    "storeFolder"
  ],
  "type": "object"
}

=== tyorka-shop/admin.tyorka.com/packages/server/~config.json
{
  "$schema": "./config.schema.json",
  "storeFolder": "./store",
  "imagesFolder": "./images",
  "insta": {
    "instagram_id": "",
    "access_token": ""
  },
  "sessionService": {
    "url": "https://session.tyorka.com"
  },
  "publicSite": {
    "folder": "/var/www/tyorka.com"
  },
  "secret": "secret",
  "port": "3000"
}
